# Generated by Django 2.1.4 on 2018-12-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181206_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, default='Не выполнен', max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
